// Build-time script: reads content/blog/*.md and produces src/data/blog-data.ts
// This avoids runtime fs access which fails on Vercel serverless

import fs from "fs";
import path from "path";
import matter from "gray-matter";

const POSTS_DIR = path.resolve("content/blog");
const OUT_FILE = path.resolve("src/data/blog-data.ts");

const CATEGORY_MAP: Record<string, string> = {
  "voice-changer-tips": "Voice Changer Tips",
  "voice-changer-review": "Voice Changer Review",
  "sound-effect-tips": "Sound Effect Tips",
  "soundboard-tips": "Soundboard Tips",
  "voice-actors": "Voice Actors",
  "vocal-remover-tips": "Vocal Remover Tips",
};

function fmtDate(d: string): string {
  const date = new Date(d);
  return isNaN(date.getTime())
    ? d
    : date.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

function estimateReadTime(text: string): string {
  const words = text.split(/\s+/).length;
  return `${Math.max(1, Math.ceil(words / 200))} min read`;
}

const slugs = fs
  .readdirSync(POSTS_DIR)
  .filter((f) => f.endsWith(".md") && f !== "README.md" && f !== "manifest.csv")
  .map((f) => f.replace(/\.md$/, ""));

interface RawPost {
  slug: string;
  href: string;
  superseded: boolean;
  category: string;
  title: string;
  excerpt: string;
  image: string;
  date: string;
  isoDate: string;
  readTime: string;
  author: string;
}

const posts: RawPost[] = [];
const contentMap: Record<string, string> = {};

for (const slug of slugs) {
  const raw = fs.readFileSync(path.join(POSTS_DIR, `${slug}.md`), "utf-8");
  const { data, content } = matter(raw);
  const dateStr = data.date || "2026-01-01";
  const is301 = !!data.superseded_by;
  posts.push({
    slug,
    href: is301 ? `/${data.superseded_by}` : `/${slug}`,
    superseded: is301,
    category: CATEGORY_MAP[data.category] || data.category || "",
    title: data.title || slug,
    excerpt: (data.description || data.excerpt || "").replace(/\n/g, " ").trim(),
    image: (data.image || "").replace("dubbingai.io/blog2/", "dubbingai.io/blog/"),
    date: fmtDate(dateStr),
    isoDate: String(dateStr),
    readTime: estimateReadTime(content),
    author: data.author || "Dubbing AI Team",
  });
  contentMap[slug] = content.replace(
    /https:\/\/dubbingai\.io\/blog2\//g,
    "https://dubbingai.io/blog/",
  );
}

posts.sort((a, b) => b.isoDate.localeCompare(a.isoDate));

const ts = `// Auto-generated by scripts/build-blog-data.ts — DO NOT EDIT
import type { BlogPost } from "@/lib/blog";

export const BLOG_POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)};

export const BLOG_CONTENT: Record<string, string> = ${JSON.stringify(contentMap, null, 2)};
`;

fs.writeFileSync(OUT_FILE, ts, "utf-8");
console.log(`blog-data: wrote ${posts.length} posts to ${OUT_FILE}`);
